{{- if and .Values.rbac.create (or .Values.serviceAccount.create .Values.serviceAccount.name) }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "aegis.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "aegis.name" . }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "aegis.fullname" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "aegis.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
{{- end }}
