{{- if and .Values.controlPlane.enabled .Values.controlPlane.pdb.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "aegis.fullname" . }}-cp
  labels:
    app.kubernetes.io/name: {{ include "aegis.name" . }}
    app.kubernetes.io/component: control-plane
spec:
  minAvailable: {{ .Values.controlPlane.pdb.minAvailable }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "aegis.name" . }}
      app.kubernetes.io/component: control-plane
{{- end }}

