{{- if and .Values.agent.enabled .Values.agent.secret.create (not .Values.agent.secret.existingSecretName) (or .Values.agent.secret.bootstrapToken (gt (len (.Values.agent.secret.data | default dict)) 0)) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "aegis.fullname" . }}-agent-secret
  labels:
    app.kubernetes.io/name: {{ include "aegis.name" . }}
    app.kubernetes.io/component: agent
type: Opaque
stringData:
  {{- if .Values.agent.secret.bootstrapToken }}
  AEGIS_BOOTSTRAP_TOKEN: {{ .Values.agent.secret.bootstrapToken | quote }}
  AEGIS_CP_BEARER: {{ .Values.agent.secret.bootstrapToken | quote }}
  {{- end }}
  {{- range $k, $v := .Values.agent.secret.data }}
  {{ $k }}: {{ $v | quote }}
  {{- end }}
{{- end }}
